#Note! docker-compose.yml is the dev env by PHZ convention.
services:

  vector-db:
    image: pgvector/pgvector:pg16
    restart: always
    env_file:
     - .env.dev
    volumes:
      - ./src/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data/16:/var/lib/postgresql/data
    ports:
      - 5432:5432
    extra_hosts:
      - "host.docker.internal:host-gateway"

  dbmate:
    build:
      context: ./
      dockerfile: ./Dockerfile-dbmate
    restart: no
    env_file:
    # dbmate uses DATABASE_URL
      - .env.dev
